version: '3.8'

services:
  nestjs-app:
    container_name: my-nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:root@host.docker.internal:3306/nestjs-websocket-redis #mysql is running in your computer
      - JWT_SECRET=thisisverysekretkey
    restart: unless-stopped
    # Add resource limits here if needed
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
