version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    volumes:
      - ./.tmp/redis-data:/data
